name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: lucas2002
          POSTGRES_DB: pdsi_prot
        ports:
          - 5432:5432
          
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2

      - name: instalando o python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.6"

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: instalar dependencias
        run: pip install -r requirements.txt

      - name: Esperando o PostgreSQL ficar pronto
        run: sleep 15

      - name: Executar pytest
        env:
          DB_USER: postgres
          DB_PASSWORD: lucas2002
          DB_DATABASE: pdsi_prot
          DB_HOST: localhost
        run: pytest teste.py
